version: "3.9"

services:
  rstudio:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rstudio-dev
    ports:
      - "8787:8787"
    volumes:
      - ~/bioinfo:/home/rstudio/project
    environment:
      - PASSWORD=bioinfo
    restart: unless-stopped

